# https://docs.codecov.io/docs/codecov-yaml
# https://github.com/codecov/support/wiki/Codecov-Yaml

coverage:
  status:
    project:
      default: false
    patch:
      default: false
  ignore:
    - "**/Mocks/*"
  fixes:
    - "build/src/::src/"

comment:
  layout: "diff"
